### ISSUE TITLE
Showing related posts

### ISSUE THREAD

**Issue by mandiwise** [redacademy/mht-fall-2016#6]
I don't think the plugin you installed to show related posts is going to work for what you need. You may need to investigate rolling your own solution. Please see this article as a starting point for doing that:

https://www.elegantthemes.com/blog/tips-tricks/display-related-posts-in-wordpress

**Comment by HaninMustafa** [comment]
I added the related articles via custom field suit.. it worked
The clients need to add the desired related articles manually.
